### PR TITLE
Add Korean (Hangul) and Japanese (Hiragana and Katakana)

### PR DESCRIPTION
**Pull request by satbyy**
Tweak Tibetan GSUB again to make these fit.

### CODE REVIEW

**Comment by dscorbett** [comment]
You might also want to consider some or all of U+2E80..U+303F, U+3100..U+312F, U+3190..U+33FF, U+A960..U+A97F, U+D7B0..U+D7FF, U+FE10..U+FE1F, U+FE30..U+FE6F, U+FF00..U+FFEF, and U+1F200..U+1F2FF.

**Comment by satbyy** [comment]
That's a long list really :) We're already at 64430 glyphs after these additions of Hangul and Kana. Which of the above do you think are the "most" necessary? I think we should probably leave ~1000 glyphs for future updates to Noto fonts. It's really small space left now.

**Comment by dscorbett** [comment]
I’d say the most important for modern, non-specialty use are U+3000..U+3002, U+3005, U+3007..U+3012, U+3014..U+301C, U+3105..U+312D, U+3131..U+3163, U+31A0..U+31B5, U+31B7..U+31BB, U+31F0..U+31FF, U+FF01..U+FF60. This includes some characters in modern use for minority languages, which are less common than some characters I’ve excluded, but which are more important to the people that use them. Some of these characters are already supported by Noto Sans Yi so you could exclude them instead of including them twice.

Noto Sans is listed twice, so all its glyphs are duplicated in Go Noto Current. To further decrease the glyph count, you could remove some scripts in UAX #<span>31</span>’s [list of excluded scripts](https://unicode.org/reports/tr31/#Table_Candidate_Characters_for_Exclusion_from_Identifiers). You could also strip blocks like Ancient Symbols, Sinhala Archaic Numbers, Bamum Supplement, and Ancient Greek Musical Notation from otherwise modern fonts.

To decrease the number of lookups, you could drop 'valt', 'vchw', 'vert', 'vhal', 'vkna', 'vkrn', 'vpal', 'vrt2', and 'vrtr', since you’re already dropping the tables for vertical writing. You could also drop some of 'c2sc', 'case', 'cv<var>XX</var>', 'fwid', 'hist', 'hkna', 'hwid', 'jp78', 'jp83', 'jp90', 'lnum', 'onum', 'nlck', 'palt', 'pkna', 'pnum', 'pwid', 'qwid', 'ruby', 'smcp', 'ss<var>XX</var>', 'tnam', 'tnum', 'trad', 'twid', 'unic', and 'zero', which are certainly nice to have but might not be worth the cost.

**Comment by satbyy** [comment]
Those are really great ideas, thanks David! I'll make new PRs for those. Merging this for now.

**Pull request merged**
