### PR TITLE
Add Noto Music

### PR DESCRIPTION
**Pull request by satbyy**

### CODE REVIEW

**Comment by satbyy** [comment]
It seems that the Musical Symbols (U+1D100 - U+1D1FF) block is already included in Noto Symbols font, which has been merged for "Go Noto Contemporary".  So the "Noto Music" font brings in Byzantine Musical Symbols and Ancient Greek musical symbols --  both of which are historical and not needed for this purpose.

So we don't need this PR at all.

**Comment by dscorbett** [comment]
What do you mean? Noto Sans Symbols2 doesn’t cover the Musical Symbols block.

**Comment by satbyy** [comment]
> What do you mean? Noto Sans Symbols2 doesn’t cover the Musical Symbols block.

My bad. I looked at the wrong font. You're right that it doesn't cover Musical symbols. 

Anyway, so, after adding Noto Music, I hit the same error with "GSUB" overflow as before. Hence, I trimmed the Tibetan subset even further (please check PR code change). This works for now, but I don't know Tibetan well. Please suggest a better way if you know!

**Comment by satbyy** [comment]
Maybe Tibetan is the wrong one to optimize. Much of the GSUB size is coming from the CJK subset (NotoSansCJKscSubset-Regular.ttf) so trimming that too would help.

**Comment by dscorbett** [comment]
Trimming Tibetan seems like the best solution for now. The bulk of NotoSansCJKscSubset-Regular.ttf’s GSUB comes from its localized forms, and it would be a shame to drop support for localized forms.

FYI, GoNotoContemporary.ttf currently doesn’t support Japanese or Korean. Supporting them in NotoSansCJKscSubset-Regular.ttf will make its GSUB much larger, in which case even discarding `\.[23]` might not be enough.

**Comment by satbyy** [comment]
Thanks for your feedback.

> FYI, GoNotoContemporary.ttf currently doesn’t support Japanese or Korean. 

Are you sure? Setting the correct language displays localized glyphs for me. For example:

```
for lang in zh_CN zh_TW ja_JP ko_KR; do
    hb-view --language=$lang --unicodes="U+904D"  ~/.fonts/GoNotoContemporary.ttf;
done
```

**Comment by dscorbett** [comment]
I mean that it doesn’t support Hiragana, Katakana, or Hangul, so it can’t be used for Japanese or Korean, even if it has localized ideographs for them.

**Comment by satbyy** [comment]
Ah, are you saying that I need to include Hangul (U+1100 – U+11FF), Hiragana (U+3040 – U+309F), Katakana (U+30A0 – U+30FF) Unicode blocks? I read that Unihan IICore contains a union of all the basic characters for Chinese/Japanese/Korean, so I thought there is nothing else to be done.

**Comment by dscorbett** [comment]
Yes: International Ideographs Core is only for ideographs. It doesn’t cover other letters, symbols, or punctuation needed for CJK.

**Pull request merged**
